//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haberciyiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public string KayitId { get; set; }
        public string KayitHaberId { get; set; }
        public string KayitKategoriId { get; set; }
    
        public virtual Haberler Haberler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
