//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haberciyiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public string KullaniciId { get; set; }
        public string roleId { get; set; }
        public string KulaniciAdiSoyadi { get; set; }
        public string KullaniciSifre { get; set; }
    }
}
